spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

  security:
    user:
      name: admin
      password: admin

  datasource:
    url: jdbc:mysql://localhost:6033/db
    username: hani2003
    password: hani2003
